# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5488cf32acb6b82d52542f27b6acc1a97707ef0e979379d7d57d9b4823a27d9735329b97b83391ea6cd1108d2ff6baf07e5257e2c02b485279e9215a953a4063

test:
  secret_key_base: 36fcac5a6cf28f4a340055fd72500035777edd6448a9e4a0aa0c6dcad69496289988f8e94f32c995bbe5977767abed9c37bb15d9c89766a60cc9cec37b110426

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
